name: Hashnode Blog Posts
on:
  schedule:
    # Runs every 6 hours of the day
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with the latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOGPOSTS"
          feed_list: "https://blog.nikfp.com/rss.xml"
          template: "<div align=\"center\"><p><em><a href=$url>$title</a></em></p><p>Published on: $date</p></div>"
          max_post_count: 3
          date_format: shortDate

     
